import logging
import networkx as nx
from typing import Dict, Any, List, Tuple

logger = logging.getLogger("Fusion")

class UnionFind:
    def __init__(self, elements):
        self.parent = {e: e for e in elements}

    def find(self, i):
        if self.parent[i] == i:
            return i
        self.parent[i] = self.find(self.parent[i])
        return self.parent[i]

    def union(self, i, j):
        root_i = self.find(i)
        root_j = self.find(j)
        if root_i != root_j:
            self.parent[root_i] = root_j

def execute_pushout_fusion(session_graph: nx.DiGraph, embedded_nodes: Dict[str, Dict[str, Any]], equivalences: List[Tuple[str, str]]):
    """Executes nx.disjoint_union and collapses nodes into quotient classes via Pushout."""
    
    logger.info("Executing categorical pushout.")
    G_new = nx.DiGraph()
    
    # 1. Populate G_new
    for n_id, data in embedded_nodes.items():
        # Color initialization based on node existence. We append to a 'colors' array for WebGL blending.
        G_new.add_node(n_id, **data, colors=[1]) # Color ID 1
        
        # Add edges derived from local Triples
        for t in data.get("triples", []):
            if "subject" in t and "object" in t and "predicate" in t:
                G_new.add_edge(t["subject"], t["object"], label=t["predicate"])

    if len(session_graph.nodes) == 0:
        session_graph.update(G_new)
        return

    # 2. Disjoint Union
    G_union = nx.disjoint_union(session_graph, G_new)
    
    # Re-map equivalences to integer IDs generated by disjoint_union
    # session_graph nodes retain indexes 0..N, G_new nodes get N+1..M
    # Wait, disjoint_union strips original string IDs unless we use nx.compose!
    # Let's use compose since string IDs are semantically unique if we collapse equivalences first.
    
    # Standard pushout structure over overlapping identifiers
    # We rename G_new nodes that have equivalences to the session_graph node IDs
    mapping = {}
    for new_id, sess_id in equivalences:
        mapping[new_id] = sess_id
        
    G_new_remapped = nx.relabel_nodes(G_new, mapping, copy=True)
    
    # 3. Graph compose (Union)
    G_final = nx.compose(session_graph, G_new_remapped)
    
    # Blend colors (simulating document color combinations)
    for n in G_final.nodes:
        if n in session_graph.nodes and n in G_new_remapped.nodes:
            sess_colors = session_graph.nodes[n].get("colors", [])
            new_colors = G_new_remapped.nodes[n].get("colors", [])
            G_final.nodes[n]["colors"] = list(set(sess_colors + new_colors))
            
    session_graph.clear()
    session_graph.update(G_final)
    logger.info(f"Graph merged. Total nodes: {len(session_graph.nodes)}.")
